-- schema.sql - PostgreSQL Database Schema for AgriPOS
-- Created by: [Person A - Database]
-- 
-- Tables:
-- 1. users - Kasir & Admin accounts (FR-5)
-- 2. products - Master data produk (FR-1)
-- 3. transactions - Transaksi penjualan (FR-2)
-- 4. transaction_items - Detail items per transaksi (FR-2)
-- 5. audit_logs - Audit trail (OFR-6)

-- TODO: Implement schema.sql
-- 
-- CREATE TABLE users (
--   user_id SERIAL PRIMARY KEY,
--   username VARCHAR(50) UNIQUE NOT NULL,
--   password VARCHAR(255) NOT NULL,
--   full_name VARCHAR(100) NOT NULL,
--   role VARCHAR(20) NOT NULL CHECK (role IN ('KASIR', 'ADMIN')),
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
--
-- CREATE TABLE products (
--   product_code VARCHAR(20) PRIMARY KEY,
--   product_name VARCHAR(100) NOT NULL,
--   category VARCHAR(50) NOT NULL,
--   price DECIMAL(12,2) NOT NULL,
--   stock INT NOT NULL,
--   reorder_level INT DEFAULT 10,
--   status VARCHAR(20) DEFAULT 'NORMAL',
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
--
-- CREATE TABLE transactions (
--   transaction_id VARCHAR(30) PRIMARY KEY,
--   transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   cashier_id INT NOT NULL REFERENCES users(user_id),
--   subtotal DECIMAL(12,2) NOT NULL,
--   discount_amount DECIMAL(12,2) DEFAULT 0,
--   total_amount DECIMAL(12,2) NOT NULL,
--   payment_method VARCHAR(20) NOT NULL,
--   status VARCHAR(20) DEFAULT 'COMPLETED'
-- );
--
-- CREATE TABLE transaction_items (
--   item_id SERIAL PRIMARY KEY,
--   transaction_id VARCHAR(30) NOT NULL REFERENCES transactions(transaction_id),
--   product_code VARCHAR(20) NOT NULL REFERENCES products(product_code),
--   quantity INT NOT NULL,
--   unit_price DECIMAL(12,2) NOT NULL,
--   subtotal DECIMAL(12,2) NOT NULL
-- );
--
-- CREATE TABLE audit_logs (
--   log_id SERIAL PRIMARY KEY,
--   timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   user_id INT REFERENCES users(user_id),
--   action VARCHAR(100) NOT NULL,
--   description TEXT,
--   table_name VARCHAR(50),
--   record_id VARCHAR(50)
-- );
