-- seed.sql - Sample data for testing AgriPOS
-- Created by: [Person A - Database]
-- 
-- Sample data untuk:
-- 1. Test user accounts (kasir & admin)
-- 2. Test products (minimal 5 items berbeda kategori)
-- 3. Optional: Sample transactions

-- TODO: Implement seed.sql
-- 
-- INSERT INTO users (username, password, full_name, role) VALUES
-- ('kasir01', '123456', 'Kasir Satu', 'KASIR'),
-- ('kasir02', '123456', 'Kasir Dua', 'KASIR'),
-- ('admin01', 'admin123', 'Admin Satu', 'ADMIN');
--
-- INSERT INTO products (product_code, product_name, category, price, stock, reorder_level) VALUES
-- ('P001', 'Beras 5kg', 'Padi-padian', 75000, 50, 10),
-- ('P002', 'Jagung 2kg', 'Padi-padian', 35000, 30, 5),
-- ('P003', 'Sayuran Segar', 'Sayuran', 25000, 100, 20),
-- ('P004', 'Buah Apel', 'Buah-buahan', 50000, 20, 5),
-- ('P005', 'Telur Ayam 1kg', 'Protein', 45000, 40, 10);
